services:
  # API Server
  - type: web
    name: unexa-backend
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: ./
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: AGORA_APP_ID
        sync: false
      - key: AGORA_PRIMARY_CERTIFICATE
        sync: false
      - key: ENCRYPTION_KEY
        sync: false
      - key: ENCRYPTION_IV
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: GOOGLE_SCRIPT_URL
        sync: false
      - key: PORT
        value: 5000
