services:
  # API Server
  - type: web
    name: unexa-backend
    env: node
    plan: free
    buildCommand: npm ci
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        value: mongodb+srv://nexbyte:nexbyte@nexbyte.wplnzim.mongodb.net/unexa_new
      - key: JWT_SECRET
        value: unexa_super_app_jwt_secret_key_2024_production
      - key: CLOUDINARY_CLOUD_NAME
        value: ddw7kbm3k
      - key: CLOUDINARY_API_KEY
        value: 225359785496153
      - key: CLOUDINARY_API_SECRET
        value: BnwN8thE81szYpnMFxCMAXzDUuA
